
default: &default
  adapter: postgresql
  encoding: unicode
  # For increased performance
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: restaurant_app_development
  username: restaurant_app
  password: restaurant_app
  host: localhost

test:
  <<: *default
  database: restaurant_app_test
  username: restaurant_app
  password: restaurant_app
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
